# This file is not intended for general use. Its purpose is to dump the .obo
# files that define the cvParam accession fields into a dependency-free format
# that can be bundled with thyra.
#
# It requires the additional dependency obonet==0.2.6:
#
#     python -m pip install obonet==0.2.6
#     python thyra/metadata/ontology/dump_obo_files.py [_ms] [_uo] [_ims]
#
# with no argument meaning all three. Refresh one at a time: each table's
# labels are what the schema's vocabularies and the imzML extractor match on,
# and a CV rename that reaches one of those is a silent change of behaviour
# (see the FTICR alias in thyra/metadata/schema/vocab.py).
#
# then run the formatters over the result (`pre-commit run --all-files`), which
# is why the committed tables are black-formatted where a fresh dump is not.
#
# Adapted from pyimzml's ontology/dump_obo_files.py, which produced the tables
# this package started from and is still the route they are refreshed by. One
# thing had to change: the PSI-MS CV used to declare a term's value type as
# ``xref: value-type:xsd\:float ...`` and now declares it as ``relationship:
# has_value_type xsd:float``. The original script reads only the xref form, so
# against a current CV it would drop the data type of every term that has one
# -- 1,066 of them when this was written. Both spellings are read here.
import re
from datetime import datetime, timezone
from pathlib import Path
from pprint import pformat

ontology_sources = [
    (
        "_ms",
        "https://raw.githubusercontent.com/HUPO-PSI/psi-ms-CV/master/psi-ms.obo",
        ["MS"],
    ),
    (
        "_uo",
        "https://raw.githubusercontent.com/bio-ontology-research-group/"
        "unit-ontology/master/unit.obo",
        ["UO"],
    ),
    (
        "_ims",
        "https://raw.githubusercontent.com/imzML/imzML/"
        "f2c8b6ce2affa8d8eef74d4bfe5922c815ff4dff/imagingMS.obo",
        ["IMS"],
    ),
]

# ``xref: value-type:xsd\:float "..."`` -- the spelling the CV used until the
# relationship below replaced it. Kept so an older .obo still dumps its types.
_XREF_VALUE_TYPE = re.compile(r"^value-type:xsd\\:(\w+) ")

# ``relationship: has_value_type xsd:float ! ...`` -- the current spelling.
_RELATIONSHIP_VALUE_TYPE = re.compile(r"^has_value_type\s+xsd:(\w+)")


def _data_type(node):
    """The ``xsd:`` type a term declares, in either spelling, or ``None``."""
    for xref in node.get("xref", []):
        match = _XREF_VALUE_TYPE.match(xref)
        if match:
            return "xsd:" + match[1]
    for relationship in node.get("relationship", []):
        match = _RELATIONSHIP_VALUE_TYPE.match(relationship)
        if match:
            return "xsd:" + match[1]
    return None


if __name__ == "__main__":
    import sys

    import obonet

    now = datetime.now(timezone.utc).isoformat()
    here = Path(__file__).resolve().parent
    wanted = set(sys.argv[1:]) or {name for name, _, _ in ontology_sources}

    for module_name, src, namespaces in ontology_sources:
        if module_name not in wanted:
            continue
        print(f"Parsing {module_name}")
        graph = obonet.read_obo(src, ignore_obsolete=False)
        version = graph.graph.get("data-version", "unknown")
        terms = {}
        for node_id in graph.nodes:
            node = graph.nodes[node_id]
            if any(node_id.startswith(ns) for ns in namespaces) and "name" in node:
                terms[node_id] = (node["name"], _data_type(node))

        with open(here / f"{module_name}.py", "wt", encoding="utf-8") as f:
            f.write("# DO NOT EDIT BY HAND\n")
            f.write(f"# This file was autogenerated by dump_obo_files.py at {now}\n")
            f.write(f"# Source: {src}\n")
            f.write(f"# data-version: {version}\n")
            f.write(f"terms = {pformat(terms, indent=4, width=100)}\n")
        print(f"  {len(terms)} terms, data-version {version}")
